environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: MetaVoice-1B
python_version: py311
requirements:
- torch>=2.1.0
- transformers
- librosa
- tqdm
- tiktoken==0.5.1
- audiocraft
- numpy<1.25
- ninja
- https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.3/flash_attn-2.5.3+cu122torch2.1cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
- fastapi
- uvicorn
- tyro
- deepfilternet
- pydub
- soundfile
- huggingface_hub
- scipy
- git+https://github.com/vshulman/metavoice-src.git@27275b0bef3663c22f1bf02441702f03b9ba6773
resources:
  accelerator: "A10G:2"
  cpu: '2'
  memory: 16Gi
  use_gpu: true
secrets:
  hf_access_token: "ENTER HF ACCESS TOKEN HERE"
system_packages:
- ffmpeg
